// Scrape supplier tariffs and write data/suppliers.json (+ .csv, report, change log).
//
//   node src/scrape-suppliers.ts            # all suppliers
//   node src/scrape-suppliers.ts --offline  # no network: rebuild from manual values (used in CI)

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { closeBrowser, fetchPageText } from "./lib/fetch-page.ts";
import { DATA, loadSupplierConfigs, readJson, writeJsonIfChanged, writeText } from "./lib/io.ts";
import { buildSupplier, rulesFor, urlsFor } from "./lib/tariffs.ts";
import { CALCULATORS, type CalculatorResult } from "./calculators/index.ts";
import { FIELD_KEYS, type FieldKey, type SupplierData, type SuppliersFile } from "./lib/types.ts";

const SUPPLIERS_JSON = join(DATA, "suppliers.json");
const CHANGES_JSON = join(DATA, "tariff-changes.json");

interface Change {
  date: string;
  supplier: string;
  field: FieldKey;
  from: number | null;
  to: number | null;
  source: "scraped" | "calculator" | "manual";
}

function toCsv(file: SuppliersFile): string {
  const head = ["id", "name", ...FIELD_KEYS.flatMap((k) => [k, `${k}_source`, `${k}_verified`]), "auto_curtailment", "tariff_url"];
  const esc = (v: unknown) => (/[",\n]/.test(String(v)) ? `"${String(v).replace(/"/g, '""')}"` : String(v ?? ""));
  const rows = file.suppliers.map((s) =>
    [
      s.id,
      s.name,
      ...FIELD_KEYS.flatMap((k) => [s.tariffs[k]?.value ?? "", s.tariffs[k]?.source ?? "", s.tariffs[k]?.verified ?? ""]),
      s.features.autoCurtailment,
      s.tariffUrl,
    ].map(esc).join(","),
  );
  return [head.join(","), ...rows].join("\n") + "\n";
}

function report(file: SuppliersFile, pending: string[] = []): string {
  const icon = (s: SupplierData, k: FieldKey) => {
    const v = s.tariffs[k];
    if (!v) return "–";
    if (v.source === "scraped") return "✅ scraped";
    if (v.source === "calculator") return "🧮 calculator";
    if (v.lastError) return "⚠️ scrape failed, manual";
    return "☑️ hand-checked";
  };
  const lines = [
    "# Scrape report",
    "",
    "Generated by `npm run suppliers`. ✅ scraped from the supplier site · 🧮 from the supplier's price calculator (test address) · ☑️ hand-checked on the supplier site · ⚠️ scrape failed, using the last hand-checked value · – not available. Only verified data is published.",
    "",
    `| Supplier | ${FIELD_KEYS.join(" | ")} |`,
    `| --- | ${FIELD_KEYS.map(() => "---").join(" | ")} |`,
    ...file.suppliers.map((s) => `| ${s.name} | ${FIELD_KEYS.map((k) => icon(s, k)).join(" | ")} |`),
    "",
  ];
  if (pending.length) {
    lines.push("## Not published yet", "", "No verified tariffs yet (prices only in a postcode calculator):", "", ...pending.map((n) => `- ${n}`), "");
  }
  const errors = file.suppliers.filter((s) => s.fetchError);
  if (errors.length) {
    lines.push("## Fetch errors", "", ...errors.map((s) => `- **${s.name}**: ${s.fetchError}`), "");
  }
  return lines.join("\n");
}

async function main() {
  const offline = process.argv.includes("--offline");
  const configs = await loadSupplierConfigs();
  const prevFile = await readJson<SuppliersFile>(SUPPLIERS_JSON);
  const prevById = new Map(prevFile?.suppliers.map((s) => [s.id, s]) ?? []);
  const now = new Date().toISOString();

  const suppliers: SupplierData[] = [];
  for (const cfg of configs) {
    const texts = new Map<string, string>();
    const errors: string[] = [];
    if (!offline) {
      for (const url of urlsFor(cfg)) {
        try {
          texts.set(url, await fetchPageText(url, cfg.render ?? "http"));
        } catch (e) {
          errors.push((e as Error).message);
        }
      }
    }
    let calc: CalculatorResult = {};
    if (!offline && cfg.calculator) {
      const run = CALCULATORS[cfg.calculator.adapter];
      try {
        if (!run) throw new Error(`unknown calculator adapter "${cfg.calculator.adapter}"`);
        calc = await run(cfg.calculator.testAddress);
      } catch (e) {
        errors.push(`calculator: ${(e as Error).message}`);
      }
    }
    // Offline: ignore scrape rules so no "fetch failed" errors are recorded.
    const rec = buildSupplier(offline ? { ...cfg, fields: {}, calculator: undefined } : cfg, texts, prevById.get(cfg.id), now, errors, calc);
    const ok = Object.values(rec.tariffs).filter((v) => v?.source === "scraped").length;
    const fromCalc = Object.values(rec.tariffs).filter((v) => v?.source === "calculator").length;
    console.log(
      `${cfg.id.padEnd(12)} scraped ${ok}/${rulesForCount(cfg)}` +
        (cfg.calculator ? `, calculator ${fromCalc}` : "") +
        (errors.length ? "  ERR " + errors.join("; ") : ""),
    );
    suppliers.push(rec);
  }
  await closeBrowser();

  // Only publish suppliers with at least one real value.
  const pending = suppliers.filter((s) => Object.keys(s.tariffs).length === 0);
  for (const s of pending) suppliers.splice(suppliers.indexOf(s), 1);

  const file: SuppliersFile = {
    $schema: "../schema/suppliers.schema.json",
    version: 1,
    generatedAt: now,
    currency: "EUR",
    vat: "excluded",
    suppliers,
  };

  // Change log: one entry each time a published value changes.
  const changes = (await readJson<Change[]>(CHANGES_JSON)) ?? [];
  const before = changes.length;
  for (const s of suppliers) {
    const prev = prevById.get(s.id);
    if (!prev) continue;
    for (const k of FIELD_KEYS) {
      const a = prev.tariffs[k]?.value ?? null;
      const b = s.tariffs[k]?.value ?? null;
      if (a !== b) changes.push({ date: now.slice(0, 10), supplier: s.id, field: k, from: a, to: b, source: s.tariffs[k]?.source ?? "manual" });
    }
  }

  const wrote = await writeJsonIfChanged(SUPPLIERS_JSON, file);
  if (wrote) await writeText(join(DATA, "suppliers.csv"), toCsv(file));
  if (changes.length !== before) await writeText(CHANGES_JSON, JSON.stringify(changes, null, 2) + "\n");

  const rep = report(file, pending.map((s) => s.name));
  const oldRep = await readFile(join(DATA, "REPORT.md"), "utf8").catch(() => "");
  if (rep !== oldRep) await writeText(join(DATA, "REPORT.md"), rep);

  console.log(wrote ? "suppliers.json written" : "suppliers.json unchanged");
}

function rulesForCount(cfg: Parameters<typeof rulesFor>[0]) {
  return FIELD_KEYS.filter((k) => rulesFor(cfg, k).length).length;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
